name: Publish Package to npm.pkg.github

on:
  repository_dispatch:
    types: [semantic-release] # curl -v -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/[org-name-or-username]/[repository]/dispatches -d '{ "event_type": "semantic-release" }'
  push:
    branches:
      - main

jobs:
  deploy:
    name: Release

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    runs-on: ubuntu-latest
    container:
      image: node:20-alpine3.18

    steps:
      - name: OS - Installing dep
        run: apk add curl git bash jq

      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Release
        shell: bash
        run: |
          rm -rf ./*
          git clone https://github.com/aziontech/theme.git && cd ./theme && npm install
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GIT_PKG }}
          GITHUB_TOKEN: ${{ secrets.GIT_PKG }}
          NPM_TOKEN: ${{ secrets.PKG_NPM_TOKEN }}

